version: '3.8'

services:
  web:
    build: .
    container_name: autoword_app
    ports:
      - "5000:7860"
    restart: always
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
